version: '3.8'
services:
  api:
    container_name: api
    build:
      context: '.'
      args:
        - APP_ENV=development
        - COMPOSER_NO_INTERACTION=0
    image: api
    ports:
      - 3006:80
    networks:
      - apinet  
    volumes:
      - ./src:/app
    command: bash -c "composer update --lock --prefer-source && supervisord"
  
  mysql-server:
    image: mysql:8.0
    container_name: api-db
    environment:
      MYSQL_DATABASE: api
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3306
    networks:
      - apinet  
    volumes:
      - ./src/storage/mysql:/var/lib/mysql:rw

  elasticsearch:
    image: elasticsearch:8.8.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - cluster.name=elasticsearch
      - xpack.security.enabled=false
      - 'ES_JAVA_OPTS=-Xms25m -Xmx256m'
    ports:
      - 9200:9200
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - apinet
    logging:
      driver: "json-file"
      options:
        max-size: "1m"

  kibana:
    image: kibana:8.8.0
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - apinet

volumes:
  es_data:
    driver: local

networks:
  apinet:
    name: app_network